### ISSUE TITLE
SidePanel resizer is janky

### ISSUE THREAD

**Issue by dsusskind** [appnexus/lucid#1047]
The resizing of `SidePanel` works for a single drag only. If a user drags multiple times then something is wrong with the offset and it doesn't follow the cursor properly.

Issue can be seen playing around with the SidePanel on https://appnexus.github.io/lucid/?path=/story/components-layout-sidepanel--no-modal

**Comment by jondlm** [comment]
I believe this was fixed by @pearlanre
