### ISSUE TITLE
your precompiled css file is in file called lucid.css, not index.js

### ISSUE THREAD

**Issue by lozzoc** [appnexus/lucid#1118]
node_modules/lucid-ui/dist/index.css should be `node_modules/lucid-ui/dist/lucid.css`. in your public readme it has incorrect file name ibelive.

**Comment by jondlm** [comment]
Yep, you're right! Thanks for mentioning it. I put up a PR with a fix that. I also fixed an issue where we were loading an internal only css file.

**Comment by lozzoc** [comment]
Yes I believe it is referred to as index.css on the readme. There was also an @import css in one of the file that is loading an internal package.

**Comment by jondlm** [comment]
I believe this was fixed. Thanks again for the report!
