### ISSUE TITLE
Dropzone component

### ISSUE THREAD

**Issue by oliveiraddb** [appnexus/lucid#128]
A drag and component to handle file upload. This can be something like this:

![dropzone](https://cloud.githubusercontent.com/assets/8205449/13898681/bfdf2388-edb7-11e5-8902-c8f90c5d1e4e.png)

that receives as props a custom message, style and an array of files. Maybe it could have a button aside to clear all files (and empty the array as consequence).

**Comment by jondlm** [comment]
Not sure this is high on our priority list since there's already a component for this in our internal library.

**Comment by jondlm** [comment]
Going to close this for now since we already have in internal anx-react counterpart that works.
