### ISSUE TITLE
RadioGroup tab focus should focus the selected radiobutton

### ISSUE THREAD

**Issue by astropunk** [appnexus/lucid#132]
Currently, when tabbing into a RadioGroup the first item always gains focus.  Browser behavior for the native control always tabs to the selected option.

**Comment by jondlm** [comment]
I narrowed the bug down to 54b1bea

**Comment by jondlm** [comment]
@nathaniellee Do we really need to `preventDefault` on the native element for radio buttons and check boxes? I couldn't find where a double handler was being fired.

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-380
