### ISSUE TITLE
Buttons are missing focus styling

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#135]
Need to handle the `:focus` state in css.

**Comment by jondlm** [comment]
After a conversation today, we determined that the focus styling should mimic the focus styling of checkboxes and radio buttons with the animating glow.

**Comment by alisonailea** [comment]
http://docspot.devnxs.net/projects/lucid/button-icon-164/#/components/Button

**Comment by alisonailea** [comment]
in merge https://github.com/appnexus/lucid/commit/bb4a1e133372161aeedf64ea27ff3d2899373603
