### ISSUE TITLE
Issue with multiple Dialogs

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#140]
If I have two `<Dialog isModal` instances on the page (one with isShown=false and another with isShown=true).
If the shown model is removed - i.e. not present in the next render (onEscape) - the isShown=false modal is now shown up front.

**Comment by tarun** [comment]
For now a simple workaround - wherever I have a lucid-ui/Dialog - not include it in render if `isShown=false`

`{isShown ? <Dialog isShown> ... </Dialog> : null}`

fortunately my code was structured to do that anyway with the anx-react/Modal+Dialog

**Comment by jondlm** [comment]
@tarun I'm trying to reproduce this issue but I can't seem to. Does this repo case look appropriate?

```javascript
import _ from 'lodash';
import React from 'react';
import Dialog from '../Dialog';

export default React.createClass({
	getInitialState() {
		return {
			isShown: true,
		};
	},

	handleRemove() {
		this.setState({ isShown: false })
	},

	render() {
		return (
			<div>
				{this.state.isShown ?
					<Dialog isModal isShown={true} size='small' onEscape={this.handleRemove}>
						One
					</Dialog>
				: null}

				<Dialog isModal isShown={false} size='small'>
					two
				</Dialog>
			</div>
		)
	}
});

```

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-378

**Comment by jondlm** [comment]
Could not repo, closing

**Comment by tarun** [comment]
oh, i thought i commented on this.. 
did you try toggling isShown back and forth between the two dialog instances... 
and the above example doesn't render on of the dialogs if isShown is false... for the bug to appear - both Dialogs should be in render - with just isShown being swapped
