### ISSUE TITLE
Table component

### ISSUE THREAD

**Issue by oliveiraddb** [appnexus/lucid#142]
A table element which can be set to have an **fixed header**.
Here's an example: http://tympanus.net/codrops/2014/01/09/sticky-table-headers-columns/

Other features can be added, like **column reorder**, **column resizing** and **column filtering**.

Ah, one more suggestion: **renderer**.
An object with column names as keys and functions as values where values of cells can be altered before rendered in the table.

I.e.:
`let renderer = {`
`  id: function(value, rows){`
`    return 'Id: '+value;`
`  },`
`  column2: function(value, rows){`
`    return value && value.toUpperCase();`
`  }`
`}`
`<Table rendered={renderer} />`

Cheers

**Comment by jondlm** [comment]
I believe work for this has been started by @ogupte and @danhahn

**Comment by ogupte** [comment]
we now have Table, ScrollTable, and DataTable components in master
