### ISSUE TITLE
Improve findElementsByType to work with stateful components

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#180]
Currently `filterTypes` doesn't work with components generated by `buildHybridComponent`. We should tweak `buildHybridComponent` to expose the base component type so that `filterTypes` can use that type.

Currently the workaround is to check `Component.type.displayName`.

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-377

**Comment by jondlm** [comment]
Going to close this for now since the only place we've encountered a need for this was in `VerticalListMenu` and there was a reasonable work around.
