### ISSUE TITLE
Table column cells with a `colSpan={1}` should show header border

### ISSUE THREAD

**Issue by ogupte** [appnexus/lucid#189]
Right now, if a consumer set's `colSpan={1}` on a cell in  `Thead`, the style selector for removing that border still selects it since it selects for any colspan value. It needs to ignore value of `1` since that is default.

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-376

**Comment by jacklenehan** [comment]
Should be completed by #195
