### ISSUE TITLE
Info, Primary, Warning button texts are 1px off

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#190]
Just on "short" and "small"

**Comment by jondlm** [comment]
This is showing up in chrome at least. I suspect it was introduced by c97766c

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-375

**Comment by jacklenehan** [comment]
This looks like it's a result of having `font-weight: 500` on `short` and `small`. I also don't think the 1px off has anything to do with `Info`, `Primary`, or `Warning` themselves - the CSS is the same, aside from the background color - but rather that *every other* button on the docs page is showing this issue. Long story short, it's a weird Chrome thing, probably only arises when you have buttons stacked vertically over each other. Fix would be to change `font-weight` to `400` but I don't think we care about this that much.
