### ISSUE TITLE
SingleSelect focus state

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#194]
Currently the single select button is lacking a focus state. It should mimic the existing pattern on `Button`s.

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-374

**Comment by jacklenehan** [comment]
This can be accomplished by adding the `tabindex` attribute to the `div.lucid-SingleSelect-Control` element

**Comment by sodiumjoe** [comment]
* replace the control `div` with a `Button`
* style selected state of `Button` to be flat
