### ISSUE TITLE
DropMenu should handle max height issues

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#196]
We should consider adding a `maxHeight` prop, or some equivalent solution, to `DropMenu`. There are cases where a menu goes up and can't be accessed off screen.

![image](https://cloud.githubusercontent.com/assets/3290587/14715785/0c9e8aaa-079f-11e6-9cbc-e51e20781428.png)

**Comment by alisonailea** [comment]
should this be solved with an overflow: scroll? or a widening flex-box with flex-wrap: wrap ?

**Comment by kl2735** [comment]
even tho it has a scroll bar and renders well, i do think it is better that there is a maxHeight prop that user can limit the height as they want.

**Comment by jondlm** [comment]
A temporary workaround for this issue can be achieved by adding a class like:

```
<SingleSelect className='foo'>
```

Then adding the following style:

```css
.lucid-ContextMenu-FlyOut.foo {
  max-height: 100px;
}
```

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-384

**Comment by jondlm** [comment]
We're going to remove the autoflipping in 1.0 and add a default max height instead.
