### ISSUE TITLE
`childProps` should just be lucid components

### ISSUE THREAD

**Issue by sodiumjoe** [appnexus/lucid#199]
currently `childProps` go through `createChildComponent`. It will be more flexible to simply refer to any lucid component definition in `childProps` and have any necessary metadata on that component.

`createLucidComponentDefinition` should have a default `render` method that renders `null`

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-385

**Comment by sodiumjoe** [comment]
addressed in https://github.com/appnexus/lucid/pull/212
