### ISSUE TITLE
Table border styles in FF/IE are not consistent in header or first col

### ISSUE THREAD

**Issue by ogupte** [appnexus/lucid#203]

**Comment by jondlm** [comment]
![wat](https://cloud.githubusercontent.com/assets/3290587/14793764/a50141c8-0ad5-11e6-8df6-cf07e9c4922f.gif)

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-393

**Comment by jacklenehan** [comment]
Should be completed by #195
