### ISSUE TITLE
Table header sort Caret icons bounce when hover over checkbox in same row

### ISSUE THREAD

**Issue by ogupte** [appnexus/lucid#204]

**Comment by ogupte** [comment]
<img src="https://cloud.githubusercontent.com/assets/3290587/14791807/50622596-0acc-11e6-8a3a-da3d920963e8.gif"/>

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-394

**Comment by jacklenehan** [comment]
Should be completed by #195
