### ISSUE TITLE
hybrid components throw invariant error in IE11

### ISSUE THREAD

**Issue by sodiumjoe** [appnexus/lucid#220]

**Comment by sodiumjoe** [comment]
waiting for repro steps

**Comment by jondlm** [comment]
Found [one issue with the demo page](https://github.com/appnexus/lucid/blob/v0.2.9/src/components/DataTable/examples/4.interactive-table.jsx#L171) but I don't think it's related to the core issue being talked about there.

**Comment by sodiumjoe** [comment]
There's a more general issue with how we're defining our components. Solution is to stick all of our non-standard properties on `statics`.

**Comment by sodiumjoe** [comment]
addressed in https://github.com/appnexus/lucid/pull/224
