### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#249]
Charts need a legend that describes the data.

*AC*
* Can be horizontal or vertical
* Can differentiate between bar/line/shape (redline/mock to come for that)
* Add options for ordering:
  * Initial/default data order
  * Alphabetical by metric name
  * Manual ordering

**Comment by jacklenehan** [comment]
Existing mockup: http://www.maloneydesignstudio.com/pres/appnexus/312/#home

**Comment by dmaloney01** [comment]
Test comment.

**Comment by dmaloney01** [comment]
Legend examples and styling guidelines can be found here:
http://maloneydesignstudio.com/pres/appnexus/313/

Slide 1:
This shows a variety of examples and calls out a typical use case.

Slide 2:
This shows the styling information.

**Comment by jondlm** [comment]
Awesome, thanks for the mocks!

**Comment by jondlm** [comment]
I'm also going to include chart tooltips in this ticket.
