### ISSUE TITLE
Paginator

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#252]
*AC*
* Recreate existing anx-react paginator (http://docspot.devnxs.net/projects/anx-react/latest/#Paginator) using Lucid components.

**Comment by jondlm** [comment]
@oliveiraddb is going to be working on this one.

**Comment by dmaloney01** [comment]
Some redlines for the paginator: http://maloneydesignstudio.com/pres/appnexus/315/

**Comment by sodiumjoe** [comment]
thanks @dmaloney01!

Couple quick questions:

* text styling?
* are the arrows the prev/next buttons just `&larr;` and `&rarr;`?

**Comment by dmaloney01** [comment]
Hey @sodiumjoe,
I've updated the styling. Same link: http://maloneydesignstudio.com/pres/appnexus/315/

I feel that the single select should not stand out in this case. We're choosing an option for them up front. I don't think it needs to stand out if they change it. Talking with @halseyhemingway we don't want the paginator to demand too much visual attention. I think the SingleSelect in this case should maintain it's "Gray" state even after a new selection is made.
