### ISSUE TITLE
SearchField

### ISSUE THREAD

**Issue by alisonailea** [appnexus/lucid#259]
A common use case is a TextField with a build in Search icon and basic onClick handlers similar to Autocomplete for use in forms, and searching data tables.

**Comment by jacklenehan** [comment]
Isn't this the kind of thing an application developer could easily create?

**Comment by jondlm** [comment]
Actually a search text field is a pretty common pattern in our apps. It's a unclear how it's going to interact with things like `Autocomplete`. Either way I'll post the mock here for posterity.

![search_styling](https://cloud.githubusercontent.com/assets/3290587/15432038/5d88d852-1e61-11e6-944e-6cacb656a33b.jpg)

**Comment by halseyhemingway** [comment]
@dmaloney01 Can you please add an example showing the positioning of the auto-complete box below the search field? (kind of like this but with the search-style rounded corners: https://jira.corp.appnexus.com/secure/attachment/74917/Dropdown_MultiSelect_Search_Styling.jpg) No need to show the states/functionality of the auto-complete results box; just the placement. Want to make sure we align it correctly.

**Comment by dmaloney01** [comment]
Here's a mockup of how autocomplete should be positioned under a search field:
http://maloneydesignstudio.com/pres/appnexus/321/
