### ISSUE TITLE
DataTable should have a prop for default text shown when there is no data

### ISSUE THREAD

**Issue by ogupte** [appnexus/lucid#274]

**Comment by dmaloney01** [comment]
Here are some examples and redlines for No Data messaging in tables and charts:
http://maloneydesignstudio.com/pres/appnexus/319/

Slides 1 & 2: Some examples in context
Slide 3: Various possible layouts. Really, we'll have a content area available. I'm not sure how particular we need to get on all of these layouts or if we just decide the amount of space people have to work with.
Slides 4 & 5: Styling notes.

Let me know if you have any questions. Also let me know how you'd like to receive the repeating background pattern. PNG, SVG (is it possible to make a repeating SVG?)

CC: @halseyhemingway

**Comment by mute** [comment]
This has been addressed.
