### ISSUE TITLE
Loading Indicators

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#276]
AC:
- A shape containing an icon (regular or animated SVG) of the developer/designer's choosing (ie could be loading indicator svg, could be success icon, etc). 
- ~~Appropriate components (*Chart, *Table, anything else?) have `loading` states available which leverage LoadingIndicator.~~  moved to #371 

Options: 
1. Title (note: in a real-worldconsole usage, we should always try to have a title)
2. Paragraph Text
3. Background cover – If this parameter is on (as it should be in most Console use cases), the background of whatever parent component this component exists within should be covered with a transparent black overlay. This helps the user understand the section of the page that this indicator relates to. (In some cases this might be the whole page).
~~4. Is Dismissable
--- Open Question: should we include a "Fade Away" parameter like we have on Banners? I think the most common use case for this is for a loading indicator, so I think most times it would be preferable that this whole component removes itself from the screen once no longer needed. So rather than a timed fade away, like on banners, this would need to accept some kind of trigger signal.~~

**Comment by halseyhemingway** [comment]
@david maloney (what is your Github user name?) – We need a redline for this. I would particularly appreciate guidance on sizing, spacing and alignment for the various text configurations there could be, as well as the opacity we want for the background cover. lmk if you have any questions!
![loading_indicators](https://cloud.githubusercontent.com/assets/3520624/15578811/f00f5656-232f-11e6-87e7-4d89001f7576.png)

**Comment by tarun** [comment]
I have a Spinner which can be used in this..

**Comment by dmaloney01** [comment]
Here are the redlines for the loading indicators:
http://maloneydesignstudio.com/pres/appnexus/320/

Slide 1 shows the indicators in various states. 
Slide 2 shows the styling guidelines. 

Please use the new loading icon spinner referenced in 281: LoadingIcon.

Let me know if you have any questions.
