### ISSUE TITLE
Grid needs to accept non-grid elements as children and use them in the proper order

### ISSUE THREAD

**Issue by alisonailea** [appnexus/lucid#278]
Currently adding a non `Grid.Cell` element inside a Grid results in the output of any `Grid.Cell` content followed by the additional elements regardless of their initial order.

**Comment by ogupte** [comment]
Really a Grid element should only have child elements which are Grid.Cell, and any content that belongs in the grid should be a child of that Grid.Cell. The other elements being appended to the end is a courtesy so the the consumer doesn't _lose_ elements, but it's not intended to accept other types. In the future we may strip out any non-Grid.Cell child elements to Grid to reduce confusion, but for now, I would refrain from doing so.
