### ISSUE TITLE
LoadingIcon

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#281]
SVG: https://appnexus.slack.com/files/ahemingway/F15DZ00J3/loading_spinner-1-1.svg

AC
* Needs to inherit `primaryColor`.

**Comment by dmaloney01** [comment]
Here's an updated loading icon to fit with our new 16px icon sizing: 
https://www.dropbox.com/s/q9e30zhbqqrd8ig/loading.svg?dl=0

**Comment by dmaloney01** [comment]
And if that link doesn't work, try this one: http://maloneydesignstudio.com/temp/loading.svg

**Comment by jondlm** [comment]
@tarun has an indicator we might be able to use for this, make sure to reach out him before working on this one.
