### ISSUE TITLE
Bug: Marquee selection around the contents of buttons on Firefox

### ISSUE THREAD

**Issue by halseyhemingway** [appnexus/lucid#292]
Running 40.0.1

Happens with both Text:
<img width="341" alt="buttons" src="https://cloud.githubusercontent.com/assets/3520624/15728131/9e492eca-2828-11e6-9551-af20cfb806c7.gif">

And Icons:

<img width="55" alt="screen shot 2016-06-01 at 6 35 48 pm" src="https://cloud.githubusercontent.com/assets/3520624/15728257/6f14106a-2829-11e6-9d65-72073d468051.png">

**Comment by sodiumjoe** [comment]
looks like a Firefox specific thing: http://stackoverflow.com/a/3844452

Since we're doing our own focus styling that includes Firefox, it seems reasonable to just add those rules to `normalize.css` or some other top-level css file.
