### ISSUE TITLE
Button Link with Icon – Icon should also get color change on hover

### ISSUE THREAD

**Issue by halseyhemingway** [appnexus/lucid#311]
No need to include an underline on the icon, just the color change. This will help the user understand the text and icon are related and they have in face, hit the right hit target.

This GIF has weird colors and is showing black as dark teal, but you get the picture:
![link_icon](https://cloud.githubusercontent.com/assets/3520624/15863163/f89c66d2-2c9f-11e6-945a-bd1a12c35778.gif)

**Comment by jondlm** [comment]
Do you mean we should remove the underline on the text?

**Comment by jondlm** [comment]
Actually, I should have just read the title more closely. The icon isn't changing color on hover and that's the issue.
