### ISSUE TITLE
Refresh Icon

### ISSUE THREAD

**Issue by oliveiraddb** [appnexus/lucid#327]
It would be interesting if lucid has a refresh icon like the one on the image bellow.

![refresh icon](https://cloud.githubusercontent.com/assets/8205449/15938527/f5242e62-2e49-11e6-99ad-9b5a5eb5c314.png)

I can contribute to the project with this component, if you guys want.

**Comment by jacklenehan** [comment]
Correct SVG: 
[icon_refresh.svg.zip](https://github.com/appnexus/lucid/files/307867/icon_refresh.svg.zip)
