### ISSUE TITLE
Swap out primaryColor from default Chart colorset

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#353]
The dataset that gets assigned primaryColor looks "special" because of how that color is used across the rest of the page. We should swap primaryColor out for something else.

**Comment by jondlm** [comment]
Hey @dmaloney01 could you take a peek at this issue?

**Comment by jondlm** [comment]
This will be completed along with the work being done in #250 per this spec:

![newchartcolors](https://cloud.githubusercontent.com/assets/3290587/16283217/d14d85b0-3880-11e6-99ef-c2e5b517fec0.png)
