### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#376]
Mock pending from @halseyhemingway.

**Comment by jacklenehan** [comment]
@nathaniellee has some work for this in `feature/ANXR-200-tag`.

**Comment by jacklenehan** [comment]
Here's where we are now: http://maloneydesignstudio.com/pres/appnexus/332/

**Comment by jondlm** [comment]
I think there's some more work being done on the design of these.

**Comment by jacklenehan** [comment]
Need to port UX and visual design from anx-react Tags.
