### ISSUE TITLE
Sticky Rows/Headers

### ISSUE THREAD

**Issue by strunkandwhite** [appnexus/lucid#383]
_AC_
- Tables have sticky headers
- Tables include ability to "freeze" the columns
- Tables have a drop-shadow on the right side if the table extends past the current browser viewport

**Comment by jacklenehan** [comment]
Comment from @dmaloney01 on old ticket: 

> This is great! And yes, I do think we should add the dropshadow under the header when it's sticky like this.
I'm thinking this is the shadow that would be a good starting point: 0px 0px 30px 0px rgba(0,0,0,0.4); 
That is the same shadow that would be used on the left or right side when we have overflow content.

**Comment by jondlm** [comment]
We've decided to add this to `DataTable`. I'm getting close to a PR.
