### ISSUE TITLE
Paginator onPageSelect is firing twice for blur and arrow button click

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#392]
- Don't fire the `onPageSelect` if the page number hasn't changed
- Investigate the double firing when the user enters a value, then blurs and clicks on the arrow all in the same motion

It's not reproducible in the docs page because it isn't wired up to a redux store that's listening to the `onPageSelect`.

**Comment by sodiumjoe** [comment]
Pretty sure `onPageSelect` is getting called with the correct args in the correct order.
