### ISSUE TITLE
normalize.css

### ISSUE THREAD

**Issue by alisonailea** [appnexus/lucid#4]
adding normalize to our stack

**Comment by jondlm** [comment]
Isn't normalize a global level change? Given this is a component library I'm not sure it makes sense.

**Comment by alisonailea** [comment]
I think it might be worth importing component specific normalize rules but I still think normalize is important. Much better than a reset as normalize doesn't overwrite and remove all browser rules, it just cleans up the rough edges of browser inconsistencies before laying down custom styling.

**Comment by jondlm** [comment]
I can definitely see the value of having a per-component normalize available.

**Comment by alisonailea** [comment]
Added a Normalize mixin which can be added on a per-component basis https://github.com/appnexus/lucid/pull/84
