### ISSUE TITLE
Fix hover behavior for icons

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#406]
Probably involves applying the hover variants from #405

**Comment by jondlm** [comment]
![image](https://cloud.githubusercontent.com/assets/3290587/16932730/1f2b86ca-4cfd-11e6-8f2b-0b01062b0f7f.png)

See the above image for the expected behavior of icons. This is mostly a reference for myself since I'm taking this ticket.

**Comment by jacklenehan** [comment]
Being resolved in #409
