### ISSUE TITLE
Validation does not render child Validation.Error component

### ISSUE THREAD

**Issue by jhsu** [appnexus/lucid#419]
when providing the error message via a child component of `Validation.Error` to `Validation` the error messages does not show up:

```
<div>
	<Validation Error='Method one'>Content</Validation>
	<Validation>
		<Validation.Error>
			<i>Method two</i>
		</Validation.Error>
		Content
	</Validation>
</div>
```

you can replicate this by looking at the docs page: http://appnexus.github.io/lucid/#/components/Validation

**Comment by jondlm** [comment]
Yep, I'm seeing that. Working on it.

**Comment by jondlm** [comment]
I bisected the issue down to 612bb9fef450f50e2bde50943a62e9f86cc66933

Still investigating.
