### ISSUE TITLE
Paginator TextField should update when totalPages changes

### ISSUE THREAD

**Issue by reddyesha** [appnexus/lucid#431]
## Initial state

<img width="379" alt="screen shot 2016-07-22 at 11 45 28 am" src="https://cloud.githubusercontent.com/assets/4751583/17067714/d203cdd2-5001-11e6-8d48-42ea24ce074c.png">

1. `pageSize` is 10
2. `totalCount` is 45
3. `totalPages` is 5
4. Paginator `TextField` is set to 1

## Steps to reproduce
1. Edit Paginator TextField to `3` and submit
2. Update `totalCount` to 13

## Expected behavior
Paginator `totalPages` updates to 2, `TextField` updates to `1`.

## Observed behavior
Paginator `totalPages` updates to 2, `TextField` remains at `3`

<img width="385" alt="screen shot 2016-07-22 at 11 44 29 am" src="https://cloud.githubusercontent.com/assets/4751583/17067692/b80b8762-5001-11e6-9c4a-020c344ae466.png">

**Comment by sodiumjoe** [comment]
Thanks for the awesome bug report!

I think ultimately this is an issue of sending invalid data into the component. E.g.

```jsx
                <Paginator
                    selectedPageIndex={2}
                    totalCount={10}
                    pageSizeOptions={[10]}
                    hasPageSizeSelector
                />
```

is an invalid state, but it's not clear what the component can do with this.

The component reducers can ensure that state transitions are valid for parts of state that it controls, but `totalCount` doesn't fall in that scope.

I.e. if consuming code is changing `totalCount`, it's also the consuming code's responsibility to make sure `selectedPageIndex` is valid. We *could* do something in the `render` function to make sure the page number that's displayed is valid, but that would actually just hide the invalid data that's being supplied to component.

I think the most we should do in the component is do some custom `propType` check to warn on invalid inputs. I've captured that in #433
