### ISSUE TITLE
Make charts responsive

### ISSUE THREAD

**Issue by alisonailea** [appnexus/lucid#442]
width and height do not work as you would expect with SVGs. SVGs as responsive components care more about the `preserveAspectRatio` and `viewbox` attributes. The calculations currently being used to set width and height need to be used to set viewbox instead. 
Width and height should be passthrough props instead.

**Comment by jondlm** [comment]
Could you give an example of bug that's been caused by this? Is this in reference to icons?

**Comment by alisonailea** [comment]
Using charts in new apps, we weren't able to align the charts inside the Panel. We wanted the width and height of the chart to be 100%, with the chart not extending beyond the bounds of the parent or breaking it's sizing ratio.

**Comment by alisonailea** [comment]
the issue is that width and height aren't the same thing as viewport.

**Comment by jondlm** [comment]
Ahh I think that makes sense. All the charts pass through additional props to the `svg` so you should be able to apply `viewport`, etc to the charts already.

**Comment by alisonailea** [comment]
okay but what I'm saying is SVGs are built on viewports not width/height. So the default should be viewport not width/height.

**Comment by jondlm** [comment]
Right, agreed! What I mentioned is a work around until we get the default fixed.
