### ISSUE TITLE
Sidebar overflow when collapsed

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#445]
A gif is worth a 10k words.

![bug](https://cloud.githubusercontent.com/assets/3290587/17409720/4909d6ba-5a25-11e6-892e-c8a3d459957c.gif)

**Comment by sodiumjoe** [comment]
this seems like it'll have the same problem with `Portal` elements in the sidebar, too. Probably needs the same fix as `Expander`/`ExpanderPanel` (i.e. render null when collapsed)

**Comment by jondlm** [comment]
I think this will be fixed when we use react motion to power the sidebar animation.

**Comment by jondlm** [comment]
Fixed by #447

**Comment by sodiumjoe** [comment]
looks like we forgot to switch out `Sidebar`/`Submarine` to use the new `Collapsible` component implemented in https://github.com/appnexus/lucid/pull/447
