### ISSUE TITLE
Mitigate LineChart ToolTip overflow at the edges

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#454]
Can we please update the chart component so that it stretches to the width of the container, and have the first and last tooltip use a different param for the arrow/carrot - bottom left for the left-most tooltip and bottom right for the right-most tooltip so that the tooltip does not get cutoff at the end of the container.

thank you
R

**Comment by jondlm** [comment]
We already support responsive charts with the `Resizer` component. We still need to account for the first/last issue with tooltips though.

**Comment by jondlm** [comment]
@rsadres How does this look?

![test](https://cloud.githubusercontent.com/assets/3290587/17686494/ca3e5044-6321-11e6-9a9f-1a4073f6c539.gif)
