### ISSUE TITLE
SingleSelect label display bug when parent container resized

### ISSUE THREAD

**Issue by indraneel** [appnexus/lucid#456]
![cr-1138](https://cloud.githubusercontent.com/assets/444765/17678529/82eb0adc-6305-11e6-949e-a028f5545c30.gif)
![creative-ui-button-size-issue](https://cloud.githubusercontent.com/assets/444765/17678528/82e92f1e-6305-11e6-864f-baa77d0895cc.gif)

SingleSelect does this weird thing where the text splits when the surrounding window is reduced in size

One possible solution would be to reduce the font size. Another would be to progressively show fewer words from the selection.

**Comment by jondlm** [comment]
@indraneel have you tried putting a min width on the single select?

**Comment by sodiumjoe** [comment]
probably should have `white-space: nowrap;` like `Button`?

**Comment by jondlm** [comment]
That would work too probably

**Comment by jondlm** [comment]
Fixed by #460
