### ISSUE TITLE
Cannot set `ref` on most components

### ISSUE THREAD

**Issue by joelgriffith** [appnexus/lucid#466]
Consider this use-case:
- A checkbox is clicked to "check" it
- A sibling `TextField` will focus when the prior checkbox is activated.

The only way to do this in React is via `ref`s. Unfortunately, lucid doesn't seem to pass-through the `ref` property to down-stream native elements.

[More about refs here](https://facebook.github.io/react/docs/more-about-refs.html)

Here's their example of doing this without any deprecated methods:

``` javascript
var MyComponent = React.createClass({
  handleClick: function() {
    // Explicitly focus the text input using the raw DOM API.
    if (this.myTextInput !== null) {
      this.myTextInput.focus();
    }
  },
  render: function() {
    // The ref attribute is a callback that saves a reference to the
    // component to this.myTextInput when the component is mounted.
    return (
      <div>
        <input type="text" ref={(ref) => this.myTextInput = ref} />
        <input
          type="button"
          value="Focus the text input"
          onClick={this.handleClick}
        />
      </div>
    );
  }
});

ReactDOM.render(
  <MyComponent />,
  document.getElementById('example')
);
```

**Comment by joelgriffith** [comment]
I could have easily missed this, but I didn't see anything mentioning `ref` in examples or source code.

**Comment by ogupte** [comment]
you cannot pass refs down to child components. refs will always get you either the DOM node or the component instance. If you put a ref on a lucid component, you'll get the instance of that component back and then you can get the DOM node for it with `ReactDOM.findDOMNode(this.myTextInput)` and do stuff with the dom node.
