### ISSUE TITLE
Moar iconz!

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#467]
Add the following icons:

- AppsIcon
- ExcludeIcon
- ExcludeLightIcon
- HelpCenterIcon
- NotificationsIcon
- ReportingIcon

**Comment by ogupte** [comment]
We should be sure to give these icons descriptive (not contextual) names.

**Comment by jondlm** [comment]
Agreed, how about:

- AppsIcon -> FourSquaresIcon
- ExcludeIcon -> MinusCircleIcon
- ExcludeLightIcon -> MinusCircleLightIcon
- HelpCenterIcon -> QuestionMarkCircleIcon
- NotificationsIcon -> BellIcon
- ReportingIcon -> ClockIcon

**Comment by jondlm** [comment]
CC @dmaloney01 this is something we thought about in retrospect. We should probably make the names of icons as descriptive as possible and put their semantic definitions in the descriptions.
