### ISSUE TITLE
Add isDisabled prop to Icon

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#470]
First we'll need to figure out if this is possible. I'm not exactly sure how we want to implement this one. Changing the `fill` is not going to work for all icons since some (e.g. `DangerIcon`) won't take `fill` changes at the top level.

**Comment by jacklenehan** [comment]
![geoiconstates](https://cloud.githubusercontent.com/assets/675987/19663212/e311f1ac-99ef-11e6-85c9-9f7a1051f763.jpg)
