### ISSUE TITLE
SingleSelect w/ search

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#479]
A few things to note about this:

- I'm not sure if it should be an entirely new component or just an addition to `SingleSelect`
- We need to make sure it has an `isLoading` prop to handle asynchronous loading of options @dmaloney01 might need to weigh in on that unless he just wants the `LoadingIndicator` to be used

![dropdown_singleselect_searchfilter_styling](https://cloud.githubusercontent.com/assets/3290587/17910957/1bbc24b8-6940-11e6-9526-5ba4dc33f421.jpg)

**Comment by jondlm** [comment]
Loading state will simply be the `LoadingIcon` centered.

**Comment by jacklenehan** [comment]
Use cases so far:
- KV Targeting Module
- Publisher Grid (timezone)
