### ISSUE TITLE
Update color options for Stacked chart with 1 data set

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#482]
The stacked linechart allows you to pick a palette. When there is only 1 data set in the stacked line chart, it displays in the first color in the palette you selected. This color is usually too light. Can we please make it so that 1 data set defaults to the color in the middle of the palette set? if you are using the blue series it'll be medium blue, if you're using the purple series it'll be medium purple.

If not, can you allow for a way to specify which color to use when there is only one data set?
thank you
R

**Comment by jondlm** [comment]
I'm going to change the default of all the monochrome palettes to behave as you described. Thanks for bringing this up!

![untitled-1](https://cloud.githubusercontent.com/assets/3290587/18011120/90767b9e-6b68-11e6-9505-1f32336c21e5.png)

**Comment by rsadres** [comment]
sounds cool! not sure if I am reading the proposed version correctly. When we are using the stacked chart with 5 data sets will they still display with the lightest color on the bottom and the darkest on the top? looks like we just reordered them in your proposal. Will this be at the devs discretion to reorder them as needed?

**Comment by jondlm** [comment]
Ahh okay, you want to keep the look the same for charts with 5 series. In that case I'm not going to change anything. Devs can actually already control the order of the palette, here's an example of how to do that:

```javascript
import _ from 'lodash';
import React from 'react';
import {
	LineChart,
	chartConstants,
} from '../../../index';

const data = [
	{ x: new Date('2015-01-01T00:00:00-08:00'), apples: 2, oranges: 3, pears: 1, bananas: 7, kiwis: 5, cherries: 3 },
	{ x: new Date('2015-01-02T00:00:00-08:00'), apples: 2, oranges: 5, pears: 6, bananas: 7, kiwis: 5, cherries: 5 },
	{ x: new Date('2015-01-03T00:00:00-08:00'), apples: 3, oranges: 2, pears: 4, bananas: 7, kiwis: 5, cherries: 2 },
	{ x: new Date('2015-01-04T00:00:00-08:00'), apples: 5, oranges: 6, pears: 1, bananas: 7, kiwis: 5, cherries: 1 },
	{ x: new Date('2015-01-05T00:00:00-08:00'), apples: 4, oranges: 3, pears: 2, bananas: 7, kiwis: 5, cherries: 3 },
	{ x: new Date('2015-01-06T00:00:00-08:00'), apples: 3, oranges: 4, pears: 4, bananas: 7, kiwis: 5, cherries: 5 },
];

const p = chartConstants.PALETTE_MONOCHROME_0_5;
const newPalette = _.slice(p, 2).concat(_.slice(p, 0, 2));

export default React.createClass({
	render() {
		return (
			<LineChart
				data={data}
				yAxisFields={['apples']}
				yAxisIsStacked={true}
				yAxisTitle='Fruit Count'
				palette={newPalette}
			/>
		);
	},
});
```

## Result

![image](https://cloud.githubusercontent.com/assets/3290587/18011497/4bd27108-6b6a-11e6-8d49-2b67f5b9c32d.png)

**Comment by rsadres** [comment]
thank you!
