### ISSUE TITLE
Issue with nested Sidebar and Submarine

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#486]
[This codepen](http://codepen.io/njlg/pen/xEKKpd?editors=0110) doesn't behave as expected on Safari or FF. It appears to be an issue with overflows, but I'm not 100% sure.

**Comment by ogupte** [comment]
it's actually because the primary content pane always has `display: flex` which mean if you set the inner submarine to `flex:1` it looks like you'd expect. Really the fix for this is to no expose the primary content as a container with `display: flex` because it causes so much confusion.

**Comment by njlg** [comment]
There is a similar-ish issue with MS Edge
