### ISSUE TITLE
LineChart value of zero does not show in tooltip

### ISSUE THREAD

**Issue by ashtynmo** [appnexus/lucid#487]
http://codepen.io/ashtynmo/pen/pEzwGW

<img width="210" alt="screen shot 2016-08-30 at 11 01 47 am" src="https://cloud.githubusercontent.com/assets/17956797/18100814/38131520-6ea1-11e6-8289-2ab731797875.png">

**Comment by jondlm** [comment]
Nice catch! Definitely looks like a bug.
