### ISSUE TITLE
Please add an empty state to the chart component

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#489]
Let's create the empty state window for the charts. 

AC
* A window displays information about the no data state. This window lives above the chart layer. (the window is visible regardless of which tab is selected)
* striped 'no data' pattern appears at the top of the window
* window can contain a customizable Title
* window can contain customizable body text
* window can contain customizable image (maximum 375 x 200 px)
* window can contain customizable button (call to action)
* window width can be dependent on the width of the content, max width for window with text only is 375 px. 
* window should display in vertical and horizontal center of the chart area

designs with some specs - http://maloneydesignstudio.com/pres/appnexus/319
thank you
R

**Comment by reddyesha** [comment]
PR: https://github.com/appnexus/lucid/pull/571
