### ISSUE TITLE
Portal element of a DropMenu is not unmounted from the DOM when the menu element is closed

### ISSUE THREAD

**Issue by slaude** [appnexus/lucid#494]
See screencast here: http://screencast.com/t/qVrEjhqLBU

**Comment by ogupte** [comment]
Duplicate of #421

**Comment by jondlm** [comment]
Doesn't actually appear to be a duplicate. We'll look into it.

**Comment by jacklenehan** [comment]
Joe investigated, can't repro.

**Comment by ogupte** [comment]
i just confirmed that the leak happens on the react global reference, not on the DOM, the dom element gets cleaned up, but the component never unmounts. calling `ReactDom.unmountComponentAtNode(this.portalElement);` before the DOM cleanup should fix this.
