### ISSUE TITLE
Add a lighter variant to LoadingIndicator

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#496]
The overlay of LoadingIndicator has proven to be too dark for many use cases. We need the option for a "Light" version where the overlay is white and set to 85% opacity.

**Comment by mute** [comment]
@jondlm: Any thoughts on what the usage for this should look like?

Some options:
`<LoadingIndicator hasOverlay lightOverlay />`
`<LoadingIndicator hasOverlay overlayKind=‘light’ />`
`<LoadingIndicator hasOverlay kind=‘light’ />`
