### ISSUE TITLE
LoadingIndicator doesn't spin on IE11

### ISSUE THREAD

**Issue by mute** [appnexus/lucid#500]
On IE11 / Win7, the LoadingIndicator spinner renders statically without any spinning animation.

See below:
<img width="1011" alt="screen shot 2016-09-01 at 3 32 32 pm" src="https://cloud.githubusercontent.com/assets/730349/18186996/ede16806-705a-11e6-8ef4-1fce61c8dc2a.png">

**Comment by jondlm** [comment]
Looks like the bug was introduced in `1.8.0`.
