### ISSUE TITLE
Improve yAxisTooltipFormatter

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#519]
There are cases where it would be nice to have to unformatted value passed to the `yAxisTooltipFormatter`. Let's add another argument to the callback signature that contains the raw y value.

Current signature: 

```
(yField, yValueFormatted) => {}
```

Proposed signature:

```
(yField, yValueFormatted, yValue) => {}
```

This will need to be done in three components:

- src/components/BarChart/BarChart.jsx
- src/components/Bars/Bars.jsx
- src/components/LineChart/LineChart.jsx

**Comment by reddyesha** [comment]
Being done as part of issue #524.
