### ISSUE TITLE
Disabled tabs are still clickable for hybrid version

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#535]
<details>
  <summary>Repro gif</summary>
![bugg](https://cloud.githubusercontent.com/assets/3290587/18797280/27f3bf20-8182-11e6-8c21-92c217182c9d.gif)
</details>

**Comment by njlg** [comment]
I caused this with my change in PR #522 based on @sodiumjoe and @ogupte's feedback. I believe they thought this was the best approach. But the example probably needs to be updated to handle no changing the index when the tab is disabled.

**Comment by mute** [comment]
Fixed by #591.
