### ISSUE TITLE
Add "partially selected" state styling to Checkbox

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#547]

**Comment by jacklenehan** [comment]
Pending mocks from @dmaloney01.

**Comment by dmaloney01** [comment]
Use an 8px x 2px white rectangle that is vertically and horizontally centered within the checkbox container. Let me know if an SVG is needed for the rectangle and I'll provide it.

![indeterminatecheckbox](https://cloud.githubusercontent.com/assets/11300581/19008474/18609524-8731-11e6-9a8f-d349fe993ab1.jpg)
