### ISSUE TITLE
SearchableSingleSelect wrapping values in FF

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#562]
There has been some odd behavior observed in FireFox with this component and long values.

![image](https://cloud.githubusercontent.com/assets/3290587/19207134/f7aefeca-8ca2-11e6-91c1-9362fcb3e462.png)

After doing a little testing, `SingleSelect` doesn't seem to have this same issue, though I'm not sure why.

**Comment by mute** [comment]
This is most likely related to the wrapping of elements that it does in order to facilitate underlining matched text.

In SearchableSelect.less:
```
	&-Option-underline-match,
	&-Option-underline-post,
	&-Option-underline-pre {
		white-space: pre;
	}
```

**Comment by mute** [comment]
I'm having trouble reproducing this issue on Firefox v49.0.1:

The behavior I'm seeing is that the dropdown menu extends its width to fit content, even with very long Option labels:

<img width="535" alt="screen shot 2016-10-11 at 10 16 43 am" src="https://cloud.githubusercontent.com/assets/730349/19273819/f5942ae2-8f9b-11e6-8573-f94d6b1ad7cf.png">

**Comment by jacklenehan** [comment]
Oliver can't repro.
