### ISSUE TITLE
Tab styles are wonky in Edge

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#575]

**Comment by jacklenehan** [comment]
<img width="1444" alt="screen shot 2016-10-13 at 12 12 54 pm" src="https://cloud.githubusercontent.com/assets/675987/19363350/f988c3ca-913e-11e6-881c-f9ca0ff5fb8f.png">

**Comment by reddyesha** [comment]
I think the `border-bottom` issue was from me zooming in/out. But the progressive tab arrows are still wonky:

<img width="1500" alt="screen shot 2016-10-13 at 12 20 10 pm" src="https://cloud.githubusercontent.com/assets/4751583/19363477/8106ce0a-913f-11e6-8b65-6e61736f2fbd.png">
