### ISSUE TITLE
Error when running 'npm run dev'

### ISSUE THREAD

**Issue by mute** [appnexus/lucid#58]

**Comment by mute** [comment]
Hey there,

I'm trying to run the project locally and getting the following error from react-router:

![screen shot 2016-03-02 at 2 34 21 pm](https://cloud.githubusercontent.com/assets/730349/13478040/00d4cdde-e084-11e5-82f2-fc6af92f26f8.png)

Looks like it might be a dependency version issue?

**Comment by jondlm** [comment]
Fixed by #59

**Comment by jondlm** [comment]
Looks like we're still getting an error in the console about using a deprecated approach. I found the correct solution: https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#using-custom-histories

I'm fixing it now.
