### ISSUE TITLE
Orphan columns don't stack in the table config modal, causing it to expand horizontally

### ISSUE THREAD

**Issue by reddyesha** [appnexus/lucid#587]
## Description

Would like to see orphan columns (columns that are not part of a column group) stacked rather than have each one get a new column. The current behavior doesn't make use of the vertical space and in turn causes the modal to expand horizontally.
## Example

<img width="1729" alt="screen shot 2016-10-19 at 2 34 45 pm" src="https://cloud.githubusercontent.com/assets/4751583/19538508/39eedfca-9609-11e6-8956-ca86f4891ec5.png">
## Open Question

How important is it that we display columns in the order they are displayed in the grid?

**Comment by mute** [comment]
Created an issue in the anx-react backlog to address this.

Thanks @reddyesha!
