### ISSUE TITLE
SplitButton

### ISSUE THREAD

**Issue by jacklenehan** [appnexus/lucid#630]

**Comment by jacklenehan** [comment]
FYI @dmaloney01.

**Comment by dmaloney01** [comment]
![splitbutton_styling](https://cloud.githubusercontent.com/assets/11300581/20488438/98bf23c0-afcc-11e6-9588-8bb4a9f3223a.jpg)

@jacklenehan Here's the styling for the split button. Both the basic button styling and a guide for our other colors are included.
