### ISSUE TITLE
SingleSelect does not render properly inside RadioGroup.Label

### ISSUE THREAD

**Issue by rkaneriya** [appnexus/lucid#662]
In order to show/hide content underneath radio buttons (as they are selected), I tried using the RadioGroup component and placed selection-specific content inside the RadioGroup.Label component (with a conditional wrapper to specify whether or not it should be shown). Ex: 

```
<RadioGroup.RadioButton>
    <RadioGroup.Label>
        <span>{label}</span>
        { 
            isOptionOneSelected 
            ? <OptionOneContent />
            : null
        }
    </RadioGroup.Label>
</RadioGroup.RadioButton>
```

This generally works, but when I try to place a SingleSelect component inside RadioGroup.Label, the menu does not render when the SingleSelect is clicked. It works fine outside of RadioGroup, however. It doesn't work inside the RadioButtonLabeled component either.

**Comment by jondlm** [comment]
This ended up causing #716 and we've spun our wheels on it for long enough. Going to close this one as "wontfix".

**Comment by jondlm** [comment]
I have an idea as to how to solve this issue. I'm going to reopen it and attempt something.
