### ISSUE TITLE
ExpanderPanel's expander is bouncing the title on hover

### ISSUE THREAD

**Issue by ewestfall** [appnexus/lucid#679]
Found in Prod on Chrome

http://recordit.co/zduekckqwI

**Comment by ogupte** [comment]
after looking at this in chrome (http://appnexus.github.io/lucid/#/components/ExpanderPanel) it seems to be an issue only in your app. You may have conflicting styles that cause the jumpiness. Can you provide any context for style collisions in your app?

**Comment by jondlm** [comment]
Going to close this one unless we see another repro.
