### ISSUE TITLE
SplitButton.Button onClick handlers prevent the SplitButton from closing.

### ISSUE THREAD

**Issue by astropunk** [appnexus/lucid#736]
With the following code expanding the dropdown and clicking `foo` collapses the dropdown as expected.

```
<SplitButton>
	<SplitButton.Button>
		Foo
	</SplitButton.Button>
	<SplitButton.Button>
		Bar
	</SplitButton.Button>
</SplitButton>
```

Adding click handlers to the options prevent the dropdown from closing when the option is clicked.  Clicks outside of the options still close the dropdown. 

```
<SplitButton>
	<SplitButton.Button
		onClick={_.noop}
	>
		Foo
	</SplitButton.Button>
	<SplitButton.Button
		onClick={_.noop}
	>
		Bar
	</SplitButton.Button>
</SplitButton>
```

**Comment by mute** [comment]
I tested and it looks like this is fixed by #730.
