### ISSUE TITLE
creating function scopes in `render` impacts performance

### ISSUE THREAD

**Issue by ogupte** [appnexus/lucid#74]

**Comment by jondlm** [comment]
I'm currently working on this one. Will have PR out today.

**Comment by jondlm** [comment]
Also here's [an article](https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f#.ebwqyuiae) detailing the problem a bit more.

**Comment by jondlm** [comment]
We're debating whether this should be simply `value` or something else entirely. I'm not a huge fan of using `value` cause I feel like it's overloaded and doesn't convey the purpose well in a React app. But it's still up for debate.

**Comment by ogupte** [comment]
My thought's on what `value` means and why I think it's a terrible prop name for radio/checkbox:

`value` for an input control is supposed to come from the user: like text inputs. Names/IDs are supposed to be defined by the app for identification purposes. However, using `name` or `id` as a prop name for input controls has some legacy technical/semantic value for certain HTML elements, so it doesn't feel right to repurpose those names (since lucid components pass them thru to the native elements anyways) so logically, something like `uniqueId` makes the most sense to me as a general solution which can be applied to any kind of repeatable component.

**Comment by jondlm** [comment]
We're considering returning all the props with a callback signature of `({ event, props }) => {}`
