### ISSUE TITLE
Please replace SeparatorIcon with this SVG

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#781]
Hey!
Can we please swap this SVG in instead of the existing SeparatorIcon? This new one has a very slight sharper point, and is an SVG. I don't think the old one is.

**Comment by rsadres** [comment]
[icon_separator.svg.zip](https://github.com/appnexus/lucid/files/1056388/icon_separator.svg.zip)

**Comment by sodiumjoe** [comment]
closed by #812
