### ISSUE TITLE
Update RadioButtonLabeled and CheckboxLabeled clickable area

### ISSUE THREAD

**Issue by rkaneriya** [appnexus/lucid#797]
Update components so that the radio button and it's label are the click target for RadioButtonLabeled and CheckboxLabeled.

I've noticed a couple tickets crop up in the past about clients getting confused by our inconsistency re: "clickable areas" on radio buttons. Sometimes, the clickable area is restricted only to the button (or checkbox) itself, sometimes it's the button + its label, and sometimes it's the button + its label + everything to the right. That's a problem our apps should address. 

To help in that consistency effort, I suggest we reduce the clickable area on RadioButtonLabeled and CheckboxLabeled components to only the button/checkbox + its label. I believe that is the UX community's consensus on this. Ex: https://uxplanet.org/radio-buttons-ux-design-588e5c0a50dc.

**Comment by rsadres** [comment]
![screenshot 2017-11-15 12 09 45](https://user-images.githubusercontent.com/10146234/32849689-e86f0614-c9fd-11e7-8090-967dcedf0ab3.png)
