### ISSUE TITLE
Add light header background option to DataTable

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#799]
Please add a light column header background option to DataTable. The dark table header was more universally relevant in the past. Now, it would be useful to have a light option for use where the dark background is too heavy and distracting.

David will provide specifications.
Light background color, col separator color, bottom rule below column header.

**Comment by dmaloney01** [comment]
I've attached an image showing an example of the light header. Here are the color updates we'll use:
BG color: #f4f4f4
Border color: #e3e3e3
Text color: #333333
Sorted column bg color: #e3e3e3
Caret color: #333333

![lightheader_example](https://user-images.githubusercontent.com/11300581/28589799-3235c7ae-7145-11e7-919d-f015af400ee6.png)
