### ISSUE TITLE
Sidebar/submarine still renders a frame with isExpanded=false

### ISSUE THREAD

**Issue by ogupte** [appnexus/lucid#806]
```
<Submarine
  isExpanded={false}
  isAnimated={false}
>
```

![submarine](https://user-images.githubusercontent.com/1967266/28789909-072146ce-75dc-11e7-9715-1b0445310f39.gif)

**Comment by jondlm** [comment]
Closing this since I think it was fixed with #815. Feel free to reopen if that's not the case.
