### ISSUE TITLE
`Grid` not working correctly in IE11 and Safari

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#81]
## Safari

![image](https://cloud.githubusercontent.com/assets/3290587/13617927/1309e50a-e536-11e5-9ea2-ab1f5467a741.png)

## IE 11

![image](https://cloud.githubusercontent.com/assets/3290587/13617937/2792fd72-e536-11e5-8dad-9cece64131e1.png)

**Comment by alisonailea** [comment]
fixed in https://github.com/appnexus/lucid/pull/84
