### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by dmaloney01** [appnexus/lucid#829]
Add the attached icons:

- Delete/Trash
- Attach/Attachment

[icons.zip](https://github.com/appnexus/lucid/files/1342507/icons.zip)

**Comment by alisonailea** [comment]
Add crown icon as well. 
[CrownIcon.zip](https://github.com/appnexus/lucid/files/1345787/CrownIcon.zip)

**Comment by alisonailea** [comment]
https://github.com/appnexus/lucid/pull/837
