### ISSUE TITLE
Update button spacing styling so that it propagates 

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#830]
Update button styling so that spacing will propagate to internal libraries as well. 
Move this snippet from src/docs/index.less to inline in button examples files?

`&-examples.Button {
        > li > section {
            display: flex;
            flex-direction: column;

            > article {
                display: flex;
                margin: 5px 0;

                button:not(:last-child) { margin-right: 5px; }
            }
        }
    }`

**Comment by chrisdopuch** [comment]
@rsadres so the idea here is that there's some extra styling that's going on in just the docs less file, and we want to move that into the Button.less file so that those styles propagate to other usages of the button outside of the docs page in Lucid?

**Comment by rsadres** [comment]
No, the idea is that this styling is only meant for the docs page. Button padding is defined within the app as needed so I'm not trying to set padding all of the places buttons are used. But I would like this padding to carry through to the docs page in our internal library. That's not happening due to the way the styling was applied. I'd like all of the button docs pages to have padding, if possible.
thank you

**Comment by rsadres** [comment]
we completed this a while back, just forgot to close it.
