### ISSUE TITLE
Create Radio Icon Group component

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#850]
Create new component: a group of buttons with an icon.
This will be a visual interface for users to select one of a few options
- functions like radio buttons, only one selection can be made
- Includes:
   - group title
   - box outline
   - icon
   - selection name
   - styling for default, hover, disabled, and selected states to be attached
- to be set up so that users can populate this component with a list of selection names and corresponding icons
- ideal for 2-5 selection options

**Comment by rsadres** [comment]
![screenshot 2017-11-13 17 14 59](https://user-images.githubusercontent.com/10146234/32752218-60debc48-c896-11e7-92be-7c5e9d5c25d6.png)

**Comment by rsadres** [comment]
![screenshot 2017-11-13 17 15 38](https://user-images.githubusercontent.com/10146234/32752231-6a24bd3e-c896-11e7-8652-905af4a8dd76.png)

**Comment by alisonailea** [comment]
This was merged as a part of 851-iconGroup

**Comment by rsadres** [comment]
http://docspot.devnxs.net/projects/lucid/latest/#/components/IconSelect
