### ISSUE TITLE
Create Checkbox Icon Group

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#851]
Create new component: a group of buttons with an icon and a checkbox.
This will be a visual interface for users to select multiple of a few options

- functions like checkbox, one or more selections can be made
- Includes:
   - group title
   - box outline
   - icon
   - checkbox
   - selection name
   - styling for default, hover, disabled, and selected states to be attached
- to be set up so that users can populate this component with a list of selection names and corresponding icons
- ideal for 2-5 selection options

**Comment by rsadres** [comment]
![screenshot 2017-11-13 17 15 38](https://user-images.githubusercontent.com/10146234/32752262-85ca955e-c896-11e7-96cf-6edd9ff1434c.png)

**Comment by alisonailea** [comment]
Complete merged in 851-iconGroup

**Comment by rsadres** [comment]
this is done
http://docspot.devnxs.net/projects/lucid/latest/#/components/IconSelect
