### ISSUE TITLE
Labeled radio button component

### ISSUE THREAD

**Issue by nathaniellee** [appnexus/lucid#86]
Still discussing whether this should be a new `LabeledRadioButton` composite component that leverages `RadioButton` or some other approach (I think we're all in agreement that we don't want to add `label` as a prop to `RadioButton`).

**Comment by jondlm** [comment]
Would we want to include labeled versions of all our controls? This is a trickier question. The approach I took with `TextField` was to put an `Error` prop directly on it which leverages the `Validation` component under the hood. Should I have created a `ValidatedTextField` component instead?

**Comment by nathaniellee** [comment]
I actually do think that it would have been better to go with a `ValidatableTextField` component instead.

**Comment by jondlm** [comment]
Agreed! Will be doing that.
