### ISSUE TITLE
Update spacing between tag groups

### ISSUE THREAD

**Issue by rsadres** [appnexus/lucid#876]
- Add 6px padding right and bottom on tag group containers. 
- Remove parent container border.
- Remove extra right padding on non-removable tags (there's no remove x, so they don't need the extra right padding)

<img width="1064" alt="screen shot 2018-01-09 at 5 51 44 pm" src="https://user-images.githubusercontent.com/10146234/34836156-9fba3f60-f6bc-11e7-9aec-c3533229376b.png">

**Comment by jacklenehan** [comment]
Addressed in #907
