### ISSUE TITLE
Add tooltipFormatter Prop to Bars and BarCharts

### ISSUE THREAD

**Issue by ToddKranenburg** [appnexus/lucid#891]
Currently, the Bars component will always display a Legend component inside each Tooltip on the graph. Adding a `tooltipFormatter` prop would allow for fully customizable Tooltip content that would over-ride any `yAxisTooltipFormatter`. If no `tooltipFormatter` prop is provided, the Tooltip should display the default Legend as it does currently. This prop should also be added to the BarCharts component and passed to the child Bars component.

**Comment by sodiumjoe** [comment]
fixed by #892
