### ISSUE TITLE
ProgressBar component

### ISSUE THREAD

**Issue by slaude** [appnexus/lucid#935]
Proposing adding a ProgressBar element to the lucid component set.

# Prior art

https://getbootstrap.com/docs/4.1/components/progress/
https://material.io/design/components/progress-indicators.html#linear-progress-indicators

# Use cases

* Indicates progress in a procedure consisting of numerous discrete steps or continuous operation (such as loading, saving multiple objects in the system, progress of the user through a workflow, estimated loading time, etc.
* Indicates progress towards a non-asynchronous goal, e.g. dollar amounts vs. targets

# Implementation

* This can be easily achieved by using css flex-box and using a `width` style value on an immediate inner child which will span the given width, e.g.
```
<div className='progressBar' style={{ display: 'flex' }}>
    {/* this would occupy a third of the width of the parent, as the style property suggests */}
    <div className='progressBar-indicator', style={{ width: '33%' }}>
    </div>
</div>
```

**Comment by jondlm** [comment]
Assigning this to @liliedelamotte but we still need to draw up some mocks. cc @dmaloney01

**Comment by jondlm** [comment]
Here's a skeleton, for inspiration, of what the component code could look like (credit to @slaude):

```
import React from 'react';
import PropTypes from 'prop-types';

const style = {
	root: {
		display: 'flex',
		margin: '8px 0',
		border: '1px solid #f4f4f4',
		padding: '1px'
	}
};

export default class ProgressBar extends React.Component {
	static propTypes = {
		percent: PropTypes.number,
		children: PropTypes.any
	}

	static defaultProps = {
		children: '&nbsp'
	};

	render() {
		const {
			percent,
			children
		} = this.props;

		return (
			<div
				style={style.root}>
				<div style={{
					background: '#2abbb0',
					width: `${percent}%`,
					padding: '3px',
					textAlign: 'center'
				}}>
					{children}
				</div>
			</div>
		);
	}
}
```

We'll want to make sure the component adapts to all the lucid conventions but this is a decent example of how it might look.

**Comment by rsadres** [comment]
visual design from David - http://maloneydesignstudio.com/pres/appnexus/417/#next
Is it possible to incorporate the animation part?
Is it possible to set the Title as a prop, so we can use this bar in situations where we want to show a title and situations with no title?

**Comment by jondlm** [comment]
Yeah for sure we could include a `Title` prop. And yes those animations should be pretty straightforward to include.
