### ISSUE TITLE
Tabs `onSelect` is not idiomatic

### ISSUE THREAD

**Issue by jondlm** [appnexus/lucid#96]
Current signature on `Tabs` `onSelect`:

```
(index, props) => {}
```

Proposed signature:

```
(index, { event, props }) => {}
```

**Comment by jacklenehan** [comment]
https://jira.corp.appnexus.com/browse/ANXR-371

**Comment by sodiumjoe** [comment]
closed by https://github.com/appnexus/lucid/pull/210
